version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=global_bilgi_example
      - POSTGRES_USER=fatih
      - POSTGRES_PASSWORD=fatih
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fatih"]
      interval: 10s
      timeout: 10s
      retries: 5

  globalbilgi-example-server:
    container_name: globalbilgi-example-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/global_bilgi_example
      DATASOURCE_USERNAME: fatih
      DATASOURCE_PASSWORD: fatih
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres_network
      - globalbilgi-example-client
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5

  globalbilgi-example-client:
    container_name: globalbilgi-example-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      globalbilgi-example-server:
        condition: service_healthy
    networks:
      - globalbilgi-example-client

networks:
  postgres_network:
    driver: bridge
  globalbilgi-example-client:
    driver: bridge