spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/global_bilgi_example
    username: fatih
    password: fatih
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  accessToken:
    expirationMs: 2592000000

