spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/global_bilgi_example}
    username: ${DATASOURCE_USERNAME:fatih}
    password: ${DATASOURCE_PASSWORD:fatih}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  accessToken:
    expirationMs: 2592000000

